In [2]:
### Numpy-> Play with arrays(numbers)
### pandas-> dataset
### Matplotlib->Data visualization
### Seaborn-> Data Visualization
### Scipy->Statistical
### Sklearn->Algorithm

In [6]:
import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(1,36,5) #shift+tab->help box

array([ 1,  6, 11, 16, 21, 26, 31])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [27]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [33]:
arr=np.random.rand(5,10)
arr

array([[0.95915142, 0.95317523, 0.02376542, 0.72118239, 0.30689101,
        0.03617303, 0.48181879, 0.00691734, 0.66391796, 0.43205765],
       [0.77526515, 0.78404348, 0.48499956, 0.04832081, 0.94317369,
        0.67693755, 0.21366419, 0.22940326, 0.54771807, 0.12599282],
       [0.19948068, 0.94972479, 0.89145237, 0.75894455, 0.36078109,
        0.22198738, 0.8409952 , 0.18771838, 0.83125367, 0.66122409],
       [0.16435608, 0.87455209, 0.71138914, 0.97274869, 0.51106656,
        0.85012581, 0.65138647, 0.29136872, 0.43119675, 0.105469  ],
       [0.62188253, 0.02821003, 0.94307019, 0.87358698, 0.07778971,
        0.34447011, 0.93880317, 0.34414228, 0.33325599, 0.16831228]])

In [35]:
arr=np.random.randn(2,5)
arr

array([[-0.18493841,  0.54040935, -1.36531687, -0.01203816,  1.56746358],
       [-0.73108549,  0.76536015, -0.27749669, -1.06391812, -0.77934062]])

In [38]:
np.random.randint(2,100)

45

In [39]:
np.random.randint(20,56,100)

array([21, 30, 38, 39, 23, 23, 31, 31, 27, 53, 50, 22, 45, 34, 31, 29, 28,
       20, 33, 24, 35, 34, 32, 39, 20, 25, 29, 32, 37, 23, 33, 53, 21, 40,
       32, 26, 32, 44, 42, 55, 37, 37, 31, 29, 31, 51, 22, 22, 32, 44, 39,
       49, 35, 42, 22, 32, 44, 33, 31, 39, 22, 53, 50, 30, 39, 30, 35, 49,
       32, 31, 44, 55, 26, 26, 46, 48, 48, 45, 38, 52, 21, 55, 45, 47, 45,
       46, 33, 43, 47, 54, 55, 45, 40, 22, 32, 20, 27, 49, 27, 50])

In [4]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 8, 7, 7, 2, 3, 8, 8, 4, 3, 4, 6, 7, 9, 0, 9, 7, 8, 7, 6, 3, 6,
       9, 8, 9, 7, 4, 0, 8, 1, 2, 8, 3, 0, 8, 6, 1, 7, 5, 9, 2, 6, 4, 9,
       3, 1, 6, 1, 1, 4])

In [5]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
rand_array.max()

9

In [11]:
rand_array.argmax()

13

In [12]:
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
a.T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
a=np.random.rand(2,3)
a

array([[0.5613611 , 0.48173115, 0.81314989],
       [0.2665739 , 0.78776955, 0.27618602]])

In [17]:
a.T

array([[0.5613611 , 0.2665739 ],
       [0.48173115, 0.78776955],
       [0.81314989, 0.27618602]])

In [18]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
sample_array[0]

10

In [20]:
sample_array[2:5]

array([12, 13, 14])

In [21]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [22]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [24]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [25]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [26]:
#Two-Dimensional array

In [27]:
import numpy as sp

In [31]:
sample_matrix=sp.array([[50,20,1,23],[24,23,21,33],[56,76,42,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 42,  7]])

In [32]:
sample_matrix[1,2]

21

In [33]:
sample_matrix[0,3]

23

In [34]:
sample_matrix[2,:]

array([56, 76, 42,  7])

In [35]:
sample_matrix[2]

array([56, 76, 42,  7])

In [37]:
sample_matrix[:,(2,3)]

array([[ 1, 23],
       [21, 33],
       [42,  7]])

In [1]:
#pandas

In [2]:
import pandas as pd

In [4]:
series1=pd.Series(['A','B','C','D','E','F','G'],index=['1','2','3','4','5','6','6'])
series1

1    A
2    B
3    C
4    D
5    E
6    F
6    G
dtype: object

In [8]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.287498  0.120998  0.333749  0.008086  0.342219
B  0.980180  0.396727  0.922120  0.410336  0.770788
C  0.078327  0.153627  0.199441  0.328019  0.030743
D  0.269081  0.212422  0.076618  0.337811  0.556931
E  0.620538  0.609873  0.261940  0.877723  0.098847
F  0.401042  0.177444  0.467994  0.442283  0.904662
G  0.093768  0.421692  0.050870  0.489668  0.328457
H  0.121070  0.791968  0.149359  0.635477  0.192008

In [11]:
df1["Score1"]

A    0.287498
B    0.980180
C    0.078327
D    0.269081
E    0.620538
F    0.401042
G    0.093768
H    0.121070
Name: Score1, dtype: float64

In [20]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.287498  0.120998  0.333749  0.008086  0.342219  0.408496
B  0.980180  0.396727  0.922120  0.410336  0.770788  1.376907
C  0.078327  0.153627  0.199441  0.328019  0.030743  0.231954
D  0.269081  0.212422  0.076618  0.337811  0.556931  0.481502
E  0.620538  0.609873  0.261940  0.877723  0.098847  1.230410
F  0.401042  0.177444  0.467994  0.442283  0.904662  0.578486
G  0.093768  0.421692  0.050870  0.489668  0.328457  0.515460
H  0.121070  0.791968  0.149359  0.635477  0.192008  0.913038

In [21]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.287498  0.120998
B  0.980180  0.396727
C  0.078327  0.153627
D  0.269081  0.212422
E  0.620538  0.609873
F  0.401042  0.177444
G  0.093768  0.421692
H  0.121070  0.791968

In [23]:
df2={'ID':['10','20','30','40'],'Name':['Suraj','Shruti','Sahil','Ajay'],'P_name':['Shruti','Suraj','Priya','Monika']}
df=pd.DataFrame(df2)
df

ID    Name  P_name
0  10   Suraj  Shruti
1  20  Shruti   Suraj
2  30   Sahil   Priya
3  40    Ajay  Monika

In [24]:
df["ID"]

0    10
1    20
2    30
3    40
Name: ID, dtype: object

In [26]:
df[["ID","Name"]]

ID    Name
0  10   Suraj
1  20  Shruti
2  30   Sahil
3  40    Ajay

In [31]:
df=df.drop("Name",axis=1)
df

P_name
0  Shruti
1   Suraj
2   Priya
3  Monika

df.drop(1)
df

In [33]:
df.drop(3)
df

P_name
0  Shruti
1   Suraj
2   Priya
3  Monika